### ISSUE TITLE
"You don't have permission to delete buffers in this workspace."

### ISSUE THREAD

**Issue by neverfox** [ardumont/emacs-live-packs#4]
Since installing these packs to a fresh emacs/emacs-live installation (via the deploy.sh method), I'm getting the occasional "You don't have permission to delete buffers in this workspace." message in the mini-buffer, usually during a file save (and when starting the daemon). It doesn't appear to have any negative effects but it's disconcerting. Any idea what could be causing it?

OS X 10.10, Emacs.app 24.5, emacs-live 1.0beta26

**Comment by proger** [comment]
A quick grep shows it's floobits from `power-pack`. Avoided the message by removing it (though there should be a better way for those who actually use it)

**Comment by neverfox** [comment]
So it is, indeed. I'll probably just disable it as well since I don't use it.
